/**
 * Copyright 2016-present, Bkav, Cop.
 * All rights reserved.
 *
 * This source code is licensed under the Bkav license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 *
 * @author phucnhb@bkav.com on 10/6/20.
 *
 * History:
 * @modifier abc@bkav.com on xx/xx/xxxx đã chỉnh sửa abcxyx (Chỉ các thay đổi quan trọng mới cần ghi lại note này)
 */
'use strict';

export const gates = [
  {id: 'Móng Cái', name: 'Móng Cái'},
  {id: 'Hữu Nghị', name: 'Hữu Nghị'},
  {id: 'Tà Lùng', name: 'Tà Lùng'},
  {id: 'Thanh Thủy', name: 'Thanh Thủy'},
  {id: 'Lào Cai', name: 'Lào Cai'},
  {id: 'Tây Trang', name: 'Tây Trang'},
  {id: 'Chiềng Khương', name: 'Chiềng Khương'},
];

export const countries = [
  {id: 'Afghanistan', name: 'Afghanistan'},
  {id: 'Albania', name: 'Albania'},
  {id: 'Algeria', name: 'Algeria'},
  {id: 'American Samoa', name: 'American Samoa'},
  {id: 'Andorra', name: 'Andorra'},
  {id: 'Angola', name: 'Angola'},
  {id: 'Anguilla', name: 'Anguilla'},
  {id: 'Antarctica', name: 'Antarctica'},
  {id: 'Antigua and Barbuda', name: 'Antigua and Barbuda'},
  {id: 'Argentina', name: 'Argentina'},
  {id: 'Armenia', name: 'Armenia'},
  {id: 'Aruba', name: 'Aruba'},
  {id: 'Australia', name: 'Australia'},
  {id: 'Austria', name: 'Austria'},
  {id: 'Azerbaijan', name: 'Azerbaijan'},
  {id: 'Bahamas (the)', name: 'Bahamas (the)'},
  {id: 'Bahrain', name: 'Bahrain'},
  {id: 'Bangladesh', name: 'Bangladesh'},
  {id: 'Barbados', name: 'Barbados'},
  {id: 'Belarus', name: 'Belarus'},
  {id: 'Belgium', name: 'Belgium'},
  {id: 'Belize', name: 'Belize'},
  {id: 'Benin', name: 'Benin'},
  {id: 'Bermuda', name: 'Bermuda'},
  {id: 'Bhutan', name: 'Bhutan'},
  {
    id: 'Bolivia (Plurinational State of)',
    name: 'Bolivia (Plurinational State of)',
  },
  {
    id: 'Bonaire, Sint Eustatius and Saba',
    name: 'Bonaire, Sint Eustatius and Saba',
  },
  {id: 'Bosnia and Herzegovina', name: 'Bosnia and Herzegovina'},
  {id: 'Botswana', name: 'Botswana'},
  {id: 'Bouvet Island', name: 'Bouvet Island'},
  {id: 'Brazil', name: 'Brazil'},
  {
    id: 'British Indian Ocean Territory (the)',
    name: 'British Indian Ocean Territory (the)',
  },
  {id: 'Brunei Darussalam', name: 'Brunei Darussalam'},
  {id: 'Bulgaria', name: 'Bulgaria'},
  {id: 'Burkina Faso', name: 'Burkina Faso'},
  {id: 'Burundi', name: 'Burundi'},
  {id: 'Cabo Verde', name: 'Cabo Verde'},
  {id: 'Cambodia', name: 'Cambodia'},
  {id: 'Cameroon', name: 'Cameroon'},
  {id: 'Canada', name: 'Canada'},
  {id: 'Cayman Islands (the)', name: 'Cayman Islands (the)'},
  {
    id: 'Central African Republic (the)',
    name: 'Central African Republic (the)',
  },
  {id: 'Chad', name: 'Chad'},
  {id: 'Chile', name: 'Chile'},
  {id: 'China', name: 'China'},
  {id: 'Christmas Island', name: 'Christmas Island'},
  {id: 'Cocos (Keeling) Islands (the)', name: 'Cocos (Keeling) Islands (the)'},
  {id: 'Colombia', name: 'Colombia'},
  {id: 'Comoros (the)', name: 'Comoros (the)'},
  {
    id: 'Congo (the Democratic Republic of the)',
    name: 'Congo (the Democratic Republic of the)',
  },
  {id: 'Congo (the)', name: 'Congo (the)'},
  {id: 'Cook Islands (the)', name: 'Cook Islands (the)'},
  {id: 'Costa Rica', name: 'Costa Rica'},
  {id: 'Croatia', name: 'Croatia'},
  {id: 'Cuba', name: 'Cuba'},
  {id: 'Curaçao', name: 'Curaçao'},
  {id: 'Cyprus', name: 'Cyprus'},
  {id: 'Czechia', name: 'Czechia'},
  {id: "Côte d'Ivoire", name: "Côte d'Ivoire"},
  {id: 'Denmark', name: 'Denmark'},
  {id: 'Djibouti', name: 'Djibouti'},
  {id: 'Dominica', name: 'Dominica'},
  {id: 'Dominican Republic (the)', name: 'Dominican Republic (the)'},
  {id: 'Ecuador', name: 'Ecuador'},
  {id: 'Egypt', name: 'Egypt'},
  {id: 'El Salvador', name: 'El Salvador'},
  {id: 'Equatorial Guinea', name: 'Equatorial Guinea'},
  {id: 'Eritrea', name: 'Eritrea'},
  {id: 'Estonia', name: 'Estonia'},
  {id: 'Eswatini', name: 'Eswatini'},
  {id: 'Ethiopia', name: 'Ethiopia'},
  {
    id: 'Falkland Islands (the) [Malvinas]',
    name: 'Falkland Islands (the) [Malvinas]',
  },
  {id: 'Faroe Islands (the)', name: 'Faroe Islands (the)'},
  {id: 'Fiji', name: 'Fiji'},
  {id: 'Finland', name: 'Finland'},
  {id: 'France', name: 'France'},
  {id: 'French Guiana', name: 'French Guiana'},
  {id: 'French Polynesia', name: 'French Polynesia'},
  {
    id: 'French Southern Territories (the)',
    name: 'French Southern Territories (the)',
  },
  {id: 'Gabon', name: 'Gabon'},
  {id: 'Gambia (the)', name: 'Gambia (the)'},
  {id: 'Georgia', name: 'Georgia'},
  {id: 'Germany', name: 'Germany'},
  {id: 'Ghana', name: 'Ghana'},
  {id: 'Gibraltar', name: 'Gibraltar'},
  {id: 'Greece', name: 'Greece'},
  {id: 'Greenland', name: 'Greenland'},
  {id: 'Grenada', name: 'Grenada'},
  {id: 'Guadeloupe', name: 'Guadeloupe'},
  {id: 'Guam', name: 'Guam'},
  {id: 'Guatemala', name: 'Guatemala'},
  {id: 'Guernsey', name: 'Guernsey'},
  {id: 'Guinea', name: 'Guinea'},
  {id: 'Guinea-Bissau', name: 'Guinea-Bissau'},
  {id: 'Guyana', name: 'Guyana'},
  {id: 'Haiti', name: 'Haiti'},
  {
    id: 'Heard Island and McDonald Islands',
    name: 'Heard Island and McDonald Islands',
  },
  {id: 'Holy See (the)', name: 'Holy See (the)'},
  {id: 'Honduras', name: 'Honduras'},
  {id: 'Hong Kong', name: 'Hong Kong'},
  {id: 'Hungary', name: 'Hungary'},
  {id: 'Iceland', name: 'Iceland'},
  {id: 'India', name: 'India'},
  {id: 'Indonesia', name: 'Indonesia'},
  {id: 'Iran (Islamic Republic of)', name: 'Iran (Islamic Republic of)'},
  {id: 'Iraq', name: 'Iraq'},
  {id: 'Ireland', name: 'Ireland'},
  {id: 'Isle of Man', name: 'Isle of Man'},
  {id: 'Israel', name: 'Israel'},
  {id: 'Italy', name: 'Italy'},
  {id: 'Jamaica', name: 'Jamaica'},
  {id: 'Japan', name: 'Japan'},
  {id: 'Jersey', name: 'Jersey'},
  {id: 'Jordan', name: 'Jordan'},
  {id: 'Kazakhstan', name: 'Kazakhstan'},
  {id: 'Kenya', name: 'Kenya'},
  {id: 'Kiribati', name: 'Kiribati'},
  {
    id: "Korea (the Democratic People's Republic of)",
    name: "Korea (the Democratic People's Republic of)",
  },
  {id: 'Korea (the Republic of)', name: 'Korea (the Republic of)'},
  {id: 'Kuwait', name: 'Kuwait'},
  {id: 'Kyrgyzstan', name: 'Kyrgyzstan'},
  {
    id: "Lao People's Democratic Republic (the)",
    name: "Lao People's Democratic Republic (the)",
  },
  {id: 'Latvia', name: 'Latvia'},
  {id: 'Lebanon', name: 'Lebanon'},
  {id: 'Lesotho', name: 'Lesotho'},
  {id: 'Liberia', name: 'Liberia'},
  {id: 'Libya', name: 'Libya'},
  {id: 'Liechtenstein', name: 'Liechtenstein'},
  {id: 'Lithuania', name: 'Lithuania'},
  {id: 'Luxembourg', name: 'Luxembourg'},
  {id: 'Macao', name: 'Macao'},
  {id: 'Madagascar', name: 'Madagascar'},
  {id: 'Malawi', name: 'Malawi'},
  {id: 'Malaysia', name: 'Malaysia'},
  {id: 'Maldives', name: 'Maldives'},
  {id: 'Mali', name: 'Mali'},
  {id: 'Malta', name: 'Malta'},
  {id: 'Marshall Islands (the)', name: 'Marshall Islands (the)'},
  {id: 'Martinique', name: 'Martinique'},
  {id: 'Mauritania', name: 'Mauritania'},
  {id: 'Mauritius', name: 'Mauritius'},
  {id: 'Mayotte', name: 'Mayotte'},
  {id: 'Mexico', name: 'Mexico'},
  {
    id: 'Micronesia (Federated States of)',
    name: 'Micronesia (Federated States of)',
  },
  {id: 'Moldova (the Republic of)', name: 'Moldova (the Republic of)'},
  {id: 'Monaco', name: 'Monaco'},
  {id: 'Mongolia', name: 'Mongolia'},
  {id: 'Montenegro', name: 'Montenegro'},
  {id: 'Montserrat', name: 'Montserrat'},
  {id: 'Morocco', name: 'Morocco'},
  {id: 'Mozambique', name: 'Mozambique'},
  {id: 'Myanmar', name: 'Myanmar'},
  {id: 'Namibia', name: 'Namibia'},
  {id: 'Nauru', name: 'Nauru'},
  {id: 'Nepal', name: 'Nepal'},
  {id: 'Netherlands (the)', name: 'Netherlands (the)'},
  {id: 'New Caledonia', name: 'New Caledonia'},
  {id: 'New Zealand', name: 'New Zealand'},
  {id: 'Nicaragua', name: 'Nicaragua'},
  {id: 'Niger (the)', name: 'Niger (the)'},
  {id: 'Nigeria', name: 'Nigeria'},
  {id: 'Niue', name: 'Niue'},
  {id: 'Norfolk Island', name: 'Norfolk Island'},
  {
    id: 'Northern Mariana Islands (the)',
    name: 'Northern Mariana Islands (the)',
  },
  {id: 'Norway', name: 'Norway'},
  {id: 'Oman', name: 'Oman'},
  {id: 'Pakistan', name: 'Pakistan'},
  {id: 'Palau', name: 'Palau'},
  {id: 'Palestine, State of', name: 'Palestine, State of'},
  {id: 'Panama', name: 'Panama'},
  {id: 'Papua New Guinea', name: 'Papua New Guinea'},
  {id: 'Paraguay', name: 'Paraguay'},
  {id: 'Peru', name: 'Peru'},
  {id: 'Philippines (the)', name: 'Philippines (the)'},
  {id: 'Pitcairn', name: 'Pitcairn'},
  {id: 'Poland', name: 'Poland'},
  {id: 'Portugal', name: 'Portugal'},
  {id: 'Puerto Rico', name: 'Puerto Rico'},
  {id: 'Qatar', name: 'Qatar'},
  {id: 'Republic of North Macedonia', name: 'Republic of North Macedonia'},
  {id: 'Romania', name: 'Romania'},
  {id: 'Russian Federation (the)', name: 'Russian Federation (the)'},
  {id: 'Rwanda', name: 'Rwanda'},
  {id: 'Réunion', name: 'Réunion'},
  {id: 'Saint Barthélemy', name: 'Saint Barthélemy'},
  {
    id: 'Saint Helena, Ascension and Tristan da Cunha',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
  },
  {id: 'Saint Kitts and Nevis', name: 'Saint Kitts and Nevis'},
  {id: 'Saint Lucia', name: 'Saint Lucia'},
  {id: 'Saint Martin (French part)', name: 'Saint Martin (French part)'},
  {id: 'Saint Pierre and Miquelon', name: 'Saint Pierre and Miquelon'},
  {
    id: 'Saint Vincent and the Grenadines',
    name: 'Saint Vincent and the Grenadines',
  },
  {id: 'Samoa', name: 'Samoa'},
  {id: 'San Marino', name: 'San Marino'},
  {id: 'Sao Tome and Principe', name: 'Sao Tome and Principe'},
  {id: 'Saudi Arabia', name: 'Saudi Arabia'},
  {id: 'Senegal', name: 'Senegal'},
  {id: 'Serbia', name: 'Serbia'},
  {id: 'Seychelles', name: 'Seychelles'},
  {id: 'Sierra Leone', name: 'Sierra Leone'},
  {id: 'Singapore', name: 'Singapore'},
  {id: 'Sint Maarten (Dutch part)', name: 'Sint Maarten (Dutch part)'},
  {id: 'Slovakia', name: 'Slovakia'},
  {id: 'Slovenia', name: 'Slovenia'},
  {id: 'Solomon Islands', name: 'Solomon Islands'},
  {id: 'Somalia', name: 'Somalia'},
  {id: 'South Africa', name: 'South Africa'},
  {
    id: 'South Georgia and the South Sandwich Islands',
    name: 'South Georgia and the South Sandwich Islands',
  },
  {id: 'South Sudan', name: 'South Sudan'},
  {id: 'Spain', name: 'Spain'},
  {id: 'Sri Lanka', name: 'Sri Lanka'},
  {id: 'Sudan (the)', name: 'Sudan (the)'},
  {id: 'Suriname', name: 'Suriname'},
  {id: 'Svalbard and Jan Mayen', name: 'Svalbard and Jan Mayen'},
  {id: 'Sweden', name: 'Sweden'},
  {id: 'Switzerland', name: 'Switzerland'},
  {id: 'Syrian Arab Republic', name: 'Syrian Arab Republic'},
  {id: 'Taiwan', name: 'Taiwan'},
  {id: 'Tajikistan', name: 'Tajikistan'},
  {id: 'Tanzania, United Republic of', name: 'Tanzania, United Republic of'},
  {id: 'Thailand', name: 'Thailand'},
  {id: 'Timor-Leste', name: 'Timor-Leste'},
  {id: 'Togo', name: 'Togo'},
  {id: 'Tokelau', name: 'Tokelau'},
  {id: 'Tonga', name: 'Tonga'},
  {id: 'Trinidad and Tobago', name: 'Trinidad and Tobago'},
  {id: 'Tunisia', name: 'Tunisia'},
  {id: 'Turkey', name: 'Turkey'},
  {id: 'Turkmenistan', name: 'Turkmenistan'},
  {
    id: 'Turks and Caicos Islands (the)',
    name: 'Turks and Caicos Islands (the)',
  },
  {id: 'Tuvalu', name: 'Tuvalu'},
  {id: 'Uganda', name: 'Uganda'},
  {id: 'Ukraine', name: 'Ukraine'},
  {id: 'United Arab Emirates (the)', name: 'United Arab Emirates (the)'},
  {
    id: 'United Kingdom of Great Britain and Northern Ireland (the)',
    name: 'United Kingdom of Great Britain and Northern Ireland (the)',
  },
  {
    id: 'United States Minor Outlying Islands (the)',
    name: 'United States Minor Outlying Islands (the)',
  },
  {
    id: 'United States of America (the)',
    name: 'United States of America (the)',
  },
  {id: 'Uruguay', name: 'Uruguay'},
  {id: 'Uzbekistan', name: 'Uzbekistan'},
  {id: 'Vanuatu', name: 'Vanuatu'},
  {
    id: 'Venezuela (Bolivarian Republic of)',
    name: 'Venezuela (Bolivarian Republic of)',
  },
  {id: 'Việt Nam', name: 'Việt Nam'},
  {id: 'Virgin Islands (British)', name: 'Virgin Islands (British)'},
  {id: 'Virgin Islands (U.S.)', name: 'Virgin Islands (U.S.)'},
  {id: 'Wallis and Futuna', name: 'Wallis and Futuna'},
  {id: 'Western Sahara', name: 'Western Sahara'},
  {id: 'Yemen', name: 'Yemen'},
  {id: 'Zambia', name: 'Zambia'},
  {id: 'Zimbabwe', name: 'Zimbabwe'},
  {id: 'Åland Islands', name: 'Åland Islands'},
];

export const provinces = [
  {
    name: 'Tỉnh Lào Cai',
    id: '10',
  },
  {
    name: 'Tỉnh Điện Biên',
    id: '11',
  },
  {
    name: 'Tỉnh Lai Châu',
    id: '12',
  },
  {
    name: 'Tỉnh Sơn La',
    id: '14',
  },
  {
    name: 'Tỉnh Yên Bái',
    id: '15',
  },
  {
    name: 'Tỉnh Hoà Bình',
    id: '17',
  },
  {
    name: 'Tỉnh Thái Nguyên',
    id: '19',
  },
  {
    name: 'Tỉnh Lạng Sơn',
    id: '20',
  },
  {
    name: 'Tỉnh Quảng Ninh',
    id: '22',
  },
  {
    name: 'Tỉnh Bắc Giang',
    id: '24',
  },
  {
    name: 'Tỉnh Phú Thọ',
    id: '25',
  },
  {
    name: 'Tỉnh Vĩnh Phúc',
    id: '26',
  },
  {
    name: 'Tỉnh Bắc Ninh',
    id: '27',
  },
  {
    name: 'Tỉnh Hải Dương',
    id: '30',
  },
  {
    name: 'Thành phố Hải Phòng',
    id: '31',
  },
  {
    name: 'Tỉnh Hưng Yên',
    id: '33',
  },
  {
    name: 'Tỉnh Thái Bình',
    id: '34',
  },
  {
    name: 'Tỉnh Hà Nam',
    id: '35',
  },
  {
    name: 'Tỉnh Nam Định',
    id: '36',
  },
  {
    name: 'Tỉnh Ninh Bình',
    id: '37',
  },
  {
    name: 'Tỉnh Thanh Hóa',
    id: '38',
  },
  {
    name: 'Tỉnh Nghệ An',
    id: '40',
  },
  {
    name: 'Tỉnh Hà Tĩnh',
    id: '42',
  },
  {
    name: 'Tỉnh Quảng Bình',
    id: '44',
  },
  {
    name: 'Tỉnh Quảng Trị',
    id: '45',
  },
  {
    name: 'Tỉnh Thừa Thiên Huế',
    id: '46',
  },
  {
    name: 'Thành phố Đà Nẵng',
    id: '48',
  },
  {
    name: 'Tỉnh Quảng Nam',
    id: '49',
  },
  {
    name: 'Tỉnh Quảng Ngãi',
    id: '51',
  },
  {
    name: 'Tỉnh Bình Định',
    id: '52',
  },
  {
    name: 'Tỉnh Phú Yên',
    id: '54',
  },
  {
    name: 'Tỉnh Khánh Hòa',
    id: '56',
  },
  {
    name: 'Tỉnh Ninh Thuận',
    id: '58',
  },
  {
    name: 'Tỉnh Bình Thuận',
    id: '60',
  },
  {
    name: 'Tỉnh Kon Tum',
    id: '62',
  },
  {
    name: 'Tỉnh Gia Lai',
    id: '64',
  },
  {
    name: 'Tỉnh Đắk Lắk',
    id: '66',
  },
  {
    name: 'Tỉnh Đắk Nông',
    id: '67',
  },
  {
    name: 'Tỉnh Lâm Đồng',
    id: '68',
  },
  {
    name: 'Tỉnh Bình Phước',
    id: '70',
  },
  {
    name: 'Tỉnh Tây Ninh',
    id: '72',
  },
  {
    name: 'Tỉnh Bình Dương',
    id: '74',
  },
  {
    name: 'Tỉnh Đồng Nai',
    id: '75',
  },
  {
    name: 'Tỉnh Bà Rịa - Vũng Tàu',
    id: '77',
  },
  {
    name: 'Thành phố Hồ Chí Minh',
    id: '79',
  },
  {
    name: 'Tỉnh Long An',
    id: '80',
  },
  {
    name: 'Tỉnh Tiền Giang',
    id: '82',
  },
  {
    name: 'Tỉnh Bến Tre',
    id: '83',
  },
  {
    name: 'Tỉnh Trà Vinh',
    id: '84',
  },
  {
    name: 'Tỉnh Vĩnh Long',
    id: '86',
  },
  {
    name: 'Tỉnh Đồng Tháp',
    id: '87',
  },
  {
    name: 'Tỉnh An Giang',
    id: '89',
  },
  {
    name: 'Tỉnh Kiên Giang',
    id: '91',
  },
  {
    name: 'Thành phố Cần Thơ',
    id: '92',
  },
  {
    name: 'Tỉnh Hậu Giang',
    id: '93',
  },
  {
    name: 'Tỉnh Sóc Trăng',
    id: '94',
  },
  {
    name: 'Tỉnh Bạc Liêu',
    id: '95',
  },
  {
    name: 'Tỉnh Cà Mau',
    id: '96',
  },
  {
    name: 'Tỉnh Cao Bằng',
    id: '04',
  },
  {
    name: 'Tỉnh Hà Giang',
    id: '02',
  },
  {
    name: 'Thành phố Hà Nội',
    id: '01',
  },
  {
    name: 'Tỉnh Tuyên Quang',
    id: '08',
  },
  {
    name: 'Tỉnh Bắc Kạn',
    id: '06',
  },
];

export const yearBirth = [
  {id: '2020', name: '2020'},
  {id: '2019', name: '2019'},
  {id: '2018', name: '2018'},
  {id: '2017', name: '2017'},
  {id: '2016', name: '2016'},
  {id: '2015', name: '2015'},
  {id: '2014', name: '2014'},
  {id: '2013', name: '2013'},
  {id: '2012', name: '2012'},
  {id: '2011', name: '2011'},
  {id: '2010', name: '2010'},
  {id: '2009', name: '2009'},
  {id: '2008', name: '2008'},
  {id: '2007', name: '2007'},
  {id: '2006', name: '2006'},
  {id: '2005', name: '2005'},
  {id: '2004', name: '2004'},
  {id: '2003', name: '2003'},
  {id: '2002', name: '2002'},
  {id: '2001', name: '2001'},
  {id: '2000', name: '2000'},
  {id: '1999', name: '1999'},
  {id: '1998', name: '1998'},
  {id: '1997', name: '1997'},
  {id: '1996', name: '1996'},
  {id: '1995', name: '1995'},
  {id: '1994', name: '1994'},
  {id: '1993', name: '1993'},
  {id: '1992', name: '1992'},
  {id: '1991', name: '1991'},
  {id: '1990', name: '1990'},
  {id: '1989', name: '1989'},
  {id: '1988', name: '1988'},
  {id: '1987', name: '1987'},
  {id: '1986', name: '1986'},
  {id: '1985', name: '1985'},
  {id: '1984', name: '1984'},
  {id: '1983', name: '1983'},
  {id: '1982', name: '1982'},
  {id: '1981', name: '1981'},
  {id: '1980', name: '1980'},
  {id: '1979', name: '1979'},
  {id: '1978', name: '1978'},
  {id: '1977', name: '1977'},
  {id: '1976', name: '1976'},
  {id: '1975', name: '1975'},
  {id: '1974', name: '1974'},
  {id: '1973', name: '1973'},
  {id: '1972', name: '1972'},
  {id: '1971', name: '1971'},
  {id: '1970', name: '1970'},
  {id: '1969', name: '1969'},
  {id: '1968', name: '1968'},
  {id: '1967', name: '1967'},
  {id: '1966', name: '1966'},
  {id: '1965', name: '1965'},
  {id: '1964', name: '1964'},
  {id: '1963', name: '1963'},
  {id: '1962', name: '1962'},
  {id: '1961', name: '1961'},
  {id: '1960', name: '1960'},
  {id: '1959', name: '1959'},
  {id: '1958', name: '1958'},
  {id: '1957', name: '1957'},
  {id: '1956', name: '1956'},
  {id: '1955', name: '1955'},
  {id: '1954', name: '1954'},
  {id: '1953', name: '1953'},
  {id: '1952', name: '1952'},
  {id: '1951', name: '1951'},
  {id: '1950', name: '1950'},
  {id: '1949', name: '1949'},
  {id: '1948', name: '1948'},
  {id: '1947', name: '1947'},
  {id: '1946', name: '1946'},
  {id: '1945', name: '1945'},
  {id: '1944', name: '1944'},
  {id: '1943', name: '1943'},
  {id: '1942', name: '1942'},
  {id: '1941', name: '1941'},
  {id: '1940', name: '1940'},
  {id: '1939', name: '1939'},
  {id: '1938', name: '1938'},
  {id: '1937', name: '1937'},
  {id: '1936', name: '1936'},
  {id: '1935', name: '1935'},
  {id: '1934', name: '1934'},
  {id: '1933', name: '1933'},
  {id: '1932', name: '1932'},
  {id: '1931', name: '1931'},
  {id: '1930', name: '1930'},
  {id: '1929', name: '1929'},
  {id: '1928', name: '1928'},
  {id: '1927', name: '1927'},
  {id: '1926', name: '1926'},
  {id: '1925', name: '1925'},
  {id: '1924', name: '1924'},
  {id: '1923', name: '1923'},
  {id: '1922', name: '1922'},
  {id: '1921', name: '1921'},
  {id: '1920', name: '1920'},
  {id: '1919', name: '1919'},
  {id: '1918', name: '1918'},
  {id: '1917', name: '1917'},
  {id: '1916', name: '1916'},
  {id: '1915', name: '1915'},
  {id: '1914', name: '1914'},
  {id: '1913', name: '1913'},
  {id: '1912', name: '1912'},
  {id: '1911', name: '1911'},
  {id: '1910', name: '1910'},
  {id: '1909', name: '1909'},
  {id: '1908', name: '1908'},
  {id: '1907', name: '1907'},
  {id: '1906', name: '1906'},
  {id: '1905', name: '1905'},
  {id: '1904', name: '1904'},
  {id: '1903', name: '1903'},
  {id: '1902', name: '1902'},
  {id: '1901', name: '1901'},
  {id: '1900', name: '1900'},
];

export const symptomData = [
  {id: 'sot', name: 'Sốt'},
  {id: 'ho', name: 'Ho'},
  {id: 'kho_tho', name: 'Khó thở'},
  {id: 'dau_hong', name: 'Đau họng'},
  {id: 'non_buon_non', name: 'Nôn / Buồn nôn'},
  {id: 'tieu_chay', name: 'Tiêu chảy'},
  {id: 'xuat_huyet_ngoai_da', name: 'Xuất huyết ngoài da'},
  {id: 'noi_ban_ngoai_da', name: 'Nôi ban ngoài da'},
];

export const exposureHistoryData = [
  {
    id: 'exposure1',
    name:
      'Đến trang trại chăn nuôi / chợ buôn bán / động vật sống / cơ sở giết mổ động vật / tiếp xúc động vật',
  },
  {
    id: 'exposure2',
    name: 'Tiếp xúc gần (< 2m) với người mắc bênh viêm đường hô hấp nCOV',
  },
];
